### ISSUE TITLE
Spike to nullify the need for '5 minute'

### ISSUE THREAD

**Issue by phi-line** [OpenCourseAPI/OwlAPI#62]
With the introduction of the advanced scraper in #59, we may not need the original '5 minute scraper'. This issue has been brought up in #60 as we try and consolidate to a streamlined data model.

The new data from the advanced scraper could be served up with the api, and give us a consistent format for accessing the data. Right now, the two different data formats make the methods for accessing data from new and old data a pain to manage.

For this research to be done, we need to see if My Portal records incremental seat changes in the advanced dataset. If we can monitor those changes overtime, then we can verify that the advanced scraper can be used as a replacement for the old '5 minute scraper'

**Comment by madhavarshney** [comment]
Currently, this does not seem possible because in order to use the advanced data scraper, an FHDA account is needed. We can revisit this in the future to see if it is possible to circumvent this restriction, or if there is a new endpoint that is uncovered that provides the same amount of data without auth being necessary.
